name: TisotVeOd

on:
  workflow_dispatch:

  schedule:
    - cron: "13 */3 * * *"

jobs:
  search:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Install Playwright
        run: |
          playwright install chromium

      - name: Run
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python main.py
